version: '3.5'

services:
  unifi:
    image: jacobalberty/unifi:latest
    container_name: unifi
    restart: always
    environment:
      - TZ='Europe/London'
      - RUNAS_UID0=false
      - UNIFI_UID=1000
      - UNIFI_GID=1000
    volumes:
      - unifi-data:/unifi/data
      - unifi-logs:/unifi/log
    network_mode: "host"
    ports:
        - "8080:8080"
        - "8443:8443"
        - "8843:8843"
        - "8880:8880"
        - "3478:3478"
        - "6789:6789"
        - "10001:10001"

volumes:
  unifi-data:
    driver: local
    driver_opts:
      device: $HOME/contents/unifi/data
      o: bind
  unifi-logs:
    driver: local
    driver_opts:
      device: /var/log
      o: bind
